export const strongHandMap = {
  classic: [
    "A formidable display of cards.",
    "I believe the odds are in my favor.",
    "It looks like my luck is about to turn.",
    "I have a good feeling about this.",
    "Keep it cool, now.",
    "You're all in trouble now!",
    "This isn't good",
    "Do what you want, I know what I'm gonna do.",
    "Lady luck is on my side today.",
    "I suppose I'll stay in... if only to see the next card.",
    "....",
  ],
  gritty: [
    "Read 'em and weep.",
    "You're walking into a buzzsaw, kid.",
    "How's about I bring on the pain now.",
    "Time to collect, chumps.",
    "Sometimes things just line up for the taking.",
    "This is gonna sting y'all!",
    "I hope you are all ready for the pain.",
    "Of all the garbage I could have gotten, seriously?",
    "Do you smell that, fear...",
    "You're not going to like how this tastes.",
    "I've seen better hands in a trash can, but let's go.",
    "....",
  ],
  modern: [
    "Straight fire in my hand right now.",
    "This is peak performance.",
    "Ngl, this hand is mid. Sending it anyway.",
    "Send it, I feel good",
    "Dealer, pass me the sugar!",
    "The nodes are strong in this one.",
    "Max what now?",
    "This is a tanker",
    "The question is, do I have bullets or not? I'm asking you.",
    "You better hope the river drowns this fire.",
    "Oh man, really?",
    "Actual God-tier draw. No shot.",
    "We're cooking with gas now, boys.",
    "Actual God-tier draw. No shot.",
    "We're cooking with gas now, boys.",
    "This is a clip-worthy moment right here.",
    "I'm literally him/her. Check the stats.",
    "....",
  ],
  pro: [
    "The equity here is heavily weighted toward me.",
    "I've got the nuts.",
    "My range equity here is marginal, but I'll defend.",
    "Do I have weapons? I have weapons.",
    "....",
    "....",
    "....",
    "....",
  ],
  classy: [
    "A truly exquisite arrangement of cards.",
    "Fortune favors the refined, it seems.",
    "One must occasionally play the cards one is given, however dull.",
    "I wish everyone well in their upcoming turns.",
    "By the luck of grace, I guess.",
    "Remarkable really. You really dealt me these?",
    "My word. This is looking profitable.",
    "The real estate is quite lovely here, I think I'll be here for awhile.",
    "....",
  ],
};
