export const weakHandMap = {
  classic: [
    "The cards are quite shy today.",
    "One must make do with what one is dealt.",
    "It's just not in the cards for me today.",
    "Is there a black cloud over my head?",
    "This one is a doosy, that's for sure.",
    "Time to let it loose on you.",
    "Not my day, is it.",
    "Wow. Ok then.",
    "Hmph.",
    "The stars have aligned for this particular moment.",
    "....",
  ],
  gritty: [
    "Garbage in, garbage out.",
    "This hand is a total dumpster fire.",
    "What a piece of...",
    "You gotta be kiddin me!!",
    "Grrrrrrr.",
    "Something stinks in here right now, sheesh.",
    "I don't want to hear it from anyone right now!",
    "Should I just leave now?",
    "Next, please.",
    "You're looking at the winner. Just save yourself the chips now.",
    "....",
  ],
  modern: [
    "Low-key struggling here.",
    "This hand is a major 'oof'.",
    "There's no rockets in these pockets.",
    "Slick, is right. I'm sliding right now.",
    "Absolute GOAT hand. No cap.",
    "....",
  ],
  pro: [
    "Range disadvantage is real right now.",
    "Dead cards, moving on.",
    "I'm mathematically certain I'm ahead here.",
    "The SPR (Stack-to-Pot Ratio) makes this a mandatory continue.",
    "My range is extremely condensed here.",
    "I have a massive theoretical advantage on this board.",
    "....",
    "....",
    "....",
    "....",
  ],
  classy: [
    "Suboptimal, but I shall manage.",
    "Hardly the vintage I was hoping for.",
    "It is rare to see such a harmonious arrangement of suits.",
    "....",
  ],
};
