export const dialoguePool = {
  strongHand: {
    classic: [
      "A formidable display of cards.",
      "I believe the odds are in my favor.",
      "It looks like my luck is about to turn.",
      "I have a good feeling about this.",
      "Keep it cool, now.",
      "You're all in trouble now!",
      "This isn't good",
      "Do what you want, I know what I'm gonna do.",
      "Lady luck is on my side today.",
      "I suppose I'll stay in... if only to see the next card.",
      "....",
    ],
    gritty: [
      "Read 'em and weep.",
      "You're walking into a buzzsaw, kid.",
      "How's about I bring on the pain now.",
      "Time to collect, chumps.",
      "Sometimes things just line up for the taking.",
      "This is gonna sting y'all!",
      "I hope you are all ready for the pain.",
      "Of all the garbage I could have gotten, seriously?",
      "Do you smell that, fear...",
      "You're not going to like how this tastes.",
      "I've seen better hands in a trash can, but let's go.",
      "....",
    ],
    modern: [
      "Straight fire in my hand right now.",
      "This is peak performance.",
      "Ngl, this hand is mid. Sending it anyway.",
      "Send it, I feel good",
      "Dealer, pass me the sugar!",
      "The nodes are strong in this one.",
      "Max what now?",
      "This is a tanker",
      "The question is, do I have bullets or not? I'm asking you.",
      "You better hope the river drowns this fire.",
      "Oh man, really?",
      "Actual God-tier draw. No shot.",
      "We're cooking with gas now, boys.",
      "Actual God-tier draw. No shot.",
      "We're cooking with gas now, boys.",
      "This is a clip-worthy moment right here.",
      "I'm literally him/her. Check the stats.",
      "....",
    ],
    pro: [
      "The equity here is heavily weighted toward me.",
      "I've got the nuts.",
      "My range equity here is marginal, but I'll defend.",
      "Do I have weapons? I have weapons.",
      "....",
      "....",
      "....",
      "....",
    ],
    classy: [
      "A truly exquisite arrangement of cards.",
      "Fortune favors the refined, it seems.",
      "One must occasionally play the cards one is given, however dull.",
      "I wish everyone well in their upcoming turns.",
      "By the luck of grace, I guess.",
      "Remarkable really. You really dealt me these?",
      "My word. This is looking profitable.",
      "The real estate is quite lovely here, I think I'll be here for awhile.",
      "....",
    ],
  },
  weakHand: {
    classic: [
      "The cards are quite shy today.",
      "One must make do with what one is dealt.",
      "It's just not in the cards for me today.",
      "Is there a black cloud over my head?",
      "This one is a doosy, that's for sure.",
      "Time to let it loose on you.",
      "Not my day, is it.",
      "Wow. Ok then.",
      "Hmph.",
      "The stars have aligned for this particular moment.",
      "....",
    ],
    gritty: [
      "Garbage in, garbage out.",
      "This hand is a total dumpster fire.",
      "What a piece of...",
      "You gotta be kiddin me!!",
      "Grrrrrrr.",
      "Something stinks in here right now, sheesh.",
      "I don't want to hear it from anyone right now!",
      "Should I just leave now?",
      "Next, please.",
      "You're looking at the winner. Just save yourself the chips now.",
      "....",
    ],
    modern: [
      "Low-key struggling here.",
      "This hand is a major 'oof'.",
      "There's no rockets in these pockets.",
      "Slick, is right. I'm sliding right now.",
      "Absolute GOAT hand. No cap.",
      "....",
    ],
    pro: [
      "Range disadvantage is real right now.",
      "Dead cards, moving on.",
      "I'm mathematically certain I'm ahead here.",
      "The SPR (Stack-to-Pot Ratio) makes this a mandatory continue.",
      "My range is extremely condensed here.",
      "I have a massive theoretical advantage on this board.",
      "....",
      "....",
      "....",
      "....",
    ],
    classy: [
      "Suboptimal, but I shall manage.",
      "Hardly the vintage I was hoping for.",
      "It is rare to see such a harmonious arrangement of suits.",
      "....",
    ],
  },
  bluffing: {
    classic: [
      "Confidence is the soul of the game.",
      "A bold move for a bold player.",
      "I'm not worried, are you?",
      "....",
    ],
    gritty: [
      "You don't have the guts to call.",
      "I can smell your fear from here.",
      "We all know you're not going to stay in this one.",
      "This is what I'm talking about.",
      "....",
    ],
    modern: [
      "Just vibe-checking your stack.",
      "Don't overthink it, just fold.",
      "You really don't want to do that right now.",
      "Looks like I'm rabbit hunting today",
      "Trust the process, guys.",
      "Main character energy right here.",
      "I'm just playing the player, not the cards.",
      "....",
    ],
    pro: [
      "I'm polarized here, and you know it.",
      "Testing your resolve.",
      "I'm feeling the max coming on, but not for you.",
      "....",
      "....",
      "....",
    ],
    classy: [
      "Appearances can be quite... expensive.",
      "Do you truly trust your intuition?",
      "I sympathize for everyone, I truly do...",
      "....",
    ],
  },
  gloating: {
    classic: [
      "Splendid! Simply splendid.",
      "Better luck next time, my dear.",
      "This pot is already mine. I'm just letting you hold the chips for a second.",
      "This is starting to get amusing..",
      "....",
    ],
    gritty: [
      "Easiest money I made all day.",
      "Next time, bring a bigger wallet.",
      "You ever seen a man lose everything over a pair of deuces? Keep pushing.",
      "This pot is already mine. I'm just letting you hold the chips for a second.",
      "I hope you've got a bus ticket home, kid.",
      "....",
    ],
    modern: [
      "L + Ratio + No Chips.",
      "Ez game, ez life.",
      "Chat, is he actually going to call this?",
      "Full send. We don't fold in this house.",
      "Wait, that's actually a 'FeelsBadMan' for you if I have it.",
      "Imagine being this lucky. Actually unreal.",
      "What's the play here, chat? Do we send it or nah?",
      "....",
    ],
    pro: [
      "Standard result. I played the math.",
      "Don't tap the glass on the fish.",
      "Standard GTO play here, don't take it personally.",
      "....",
      "....",
    ],
    classy: [
      "A pleasure doing business with you.",
      "Quality usually prevails in the end.",
      "I find your betting style... aggressive. How primitive.",
      "A gentleman never reveals his hand, but he always collects his winnings.",
      "Is that a bluff? How wonderfully quaint.",
      "Do you always play with such... reckless abandon?",
      "....",
    ],
  },
  sulking: {
    classic: [
      "How very unfortunate.",
      "I simply cannot believe my luck.",
      "I believe the dealer has a personal vendetta against me.",
      "....",
    ],
    gritty: [
      "Complete and utter garbage.",
      "That river was a crime.",
      "Hey Dealer, you sure you shuffled these? Because this is a joke.",
      "Can you pull that knife out of my back already?",
      "This table is rigged. I can feel it.",
      "Go ahead, take it. I’ve bled more than this before.",
      "Lucky break for a bottom-feeder.",
      "I'm gonna remember that face when we're done here.",
      "Don't get used to that feeling of winning.",
      "....",
    ],
    modern: ["Absolute robbery.", "Bruh. Are you serious right now?", "...."],
    pro: [
      "One-outer. Disgusting.",
      "I played it perfectly; the deck just failed.",
      "Negative variance is a part of the game, I suppose.",
      "Completely uncharacteristic run-out.",
      "The solver says I win that 92% of the time. Unreal.",
      "....",
    ],
    classy: [
      "How utterly gauche of the dealer.",
      "A momentary lapse in the natural order.",
      "....",
    ],
  },
  neutral: {
    classic: ["The game continues.", "Interesting...", "...."],
    gritty: [
      "Just play the cards.",
      "Moving right along.",
      "Can we keep this going now please.",
      "You rats keep up now, I just want keep it moving",
      "Deal the cards. My time's expensive.",
      "Stare all you want, I ain't blinking.",
      "Just another Tuesday in the pit.",
      "Cards up, mouths shut.",
      "....",
    ],
    modern: [
      "Neutral vibes only.",
      "Next hand, let's go.",
      "Cool beans",
      "Good times, everyone.",
      "....",
    ],
    pro: [
      "Action's on you.",
      "Checking the ranges.",
      "We've got the Rock Garden here, I'll be safe",
      "....",
    ],
    classy: [
      "Proceed. I am intrigued.",
      "The atmosphere is quite pleasant.",
      "....",
    ],
  },
  nagging: {
    classic: [
      "Patience is a virtue, but time is fleeting.",
      "Shall we continue, sir?",
      "....",
    ],
    gritty: [
      "Clock's ticking. You falling asleep?",
      "I haven't got all day. Move it.",
      "....",
    ],
    modern: ["Don't lag the game, let's go.", "Hello? Anyone home?"],
    pro: [
      "I'm going to have to call 'time' soon.",
      "Keep the game moving, please.",
      "....",
    ],
    classy: [
      "Efficiency is the mark of a gentleman.",
      "Delaying the inevitable is quite tedious.",
      "....",
    ],
  },
  egging: {
    classic: [
      "A wager of this size surely requires a response.",
      "Are you quite finished?",
      "....",
    ],
    gritty: [
      "The pot ain't getting any bigger while you're staring at it.",
      "You gonna play or just hold up the line?",
      "I've seen glaciers move faster than you.",
      "Just throw the chips in and let's get to the next one.",
      "Tick-tock, pal. I've got places to be.",
    ],
    modern: [
      "Betting is the whole point, right?",
      "Send it. Full heart.",
      "Don't be a coward, click the button.",
      "Is the Wi-Fi lagging or are you just scared?",
      "Vibe check? You seem stressed.",
      "Imagine folding here. Couldn't be me.",
    ],
    pro: [
      "It's a profitable call if you have the range.",
      "You know you want to see the cards.",
      "....",
    ],
    classy: [
      "A bold bet requires an equally bold resolution.",
      "The table awaits your decision, darling.",
      "....",
    ],
  },
  baiting: {
    classic: [
      "A wager of this size surely requires a response.",
      "Are you quite finished?",
      "....",
    ],
    gritty: [
      "You look like you're looking for an excuse to fold.",
      "It’s only money. You can always make more tomorrow.",
      "I've got you right where I want you, don't I?",
      "You don't have the stomach for this bet.",
      "Go ahead, make a hero call. See what happens.",
    ],
    modern: ["Betting is the whole point, right?", "Send it. Full heart."],
    pro: [
      "It's a profitable call if you have the range.",
      "You know you want to see the cards.",
      "Are you getting the right price to call?",
      "I'm offering you 3-to-1. The math says you should stay.",
      "If you're folding there, your range is way too narrow.",
      "....",
    ],
    classy: [
      "A bold bet requires an equally bold resolution.",
      "The table awaits your decision, darling.",
      "....",
    ],
  },
};
