export const archetypeRanges = {
  gritty: {
    aggressiveness: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    bluffFrequency: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    foldThreshold: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
  },
  classic: {
    aggressiveness: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    bluffFrequency: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    foldThreshold: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
  },
  modern: {
    aggressiveness: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    bluffFrequency: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    foldThreshold: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
  },
  classy: {
    aggressiveness: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    bluffFrequency: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    foldThreshold: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
  },
  pro: {
    aggressiveness: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    bluffFrequency: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
    foldThreshold: [
      { min: 4, max: 5 },
      { min: 5, max: 6 },
      { min: 6, max: 8 },
      { min: 2, max: 3 },
    ],
  },
};
export const prefixes = [
  "Slippery",
  "Old Man",
  "Crazy",
  "Gentleman",
  "Deacon",
  "Rattlesnake",
  "Smiling",
];

export const suffixes = [
  "the Kid",
  "the Cheat",
  "Two-Times",
  "of the West",
  "Smooth",
];

export const villainPool = {
  classic: [
    "Arthur",
    "Eleanor",
    "Raymond",
    "Martha",
    "Harvey",
    "Janet",
    "Greg",
    "Bonnie",
    "Kyle",
    "Mary",
    "Clark",
    "Donna",
  ],
  gritty: [
    "Jax",
    "Mickey",
    "Sloane",
    "Rocco",
    "Vinnie",
    "Ripley",
    "Moxie",
    "Gunnar",
    "Jinx",
    "Aria",
    "Sledge",
    "Vanna",
    "Steel",
    "Gutter",
    "Tank",
    "Li",
  ],
  modern: [
    "Leo",
    "Sienna",
    "Kai",
    "Ezra",
    "Luna",
    "Ryker",
    "Nova",
    "Xiomara",
    "Rhodes",
    "Zadie",
    "Merrick",
    "Lana",
    "Vaughn",
  ],
  classy: [
    "Julian",
    "Beatrice",
    "Bob",
    "Madelaine",
    "Gemma",
    "Hubert",
    "Lindsay",
    "Veronica",
    "Winthrop",
    "Joseph",
    "Gerald",
    "Kathleen",
    "Derek",
  ],
  pro: [
    "Doyle",
    "Stu",
    "Phil",
    "Johnny",
    "Annette",
    "Barbara",
    "Linda",
    "Carlos",
    "Jennifer",
    "Michael",
  ],
};
